version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MONGODB_URI: mongodb://mongo_db-testcase:27017/moodtrackerdb
        JWT_SECRET_FALLBACK: ${JWT_SECRET_FALLBACK}
    container_name: moodtracker
    ports:
      - '3200:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo_db-testcase:27017/moodtrackerdb
      - JWT_SECRET_FALLBACK=${JWT_SECRET_FALLBACK}
      
  mongo:
    image: mongo:8
    container_name: mongo_db-testcase
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: