@echo off
echo Testing the test results formatter...

rem Create sample test output
(
echo Starting Test 1: Signup -^> Redirects into app with same details as signed up
echo 📍 Navigating to homepage...
echo 🔍 Looking for signup form...
echo 📝 Filling out registration form...
echo 🚀 Submitting registration form...
echo ⏳ Waiting for redirect after signup...
echo ✅ Test 1 passed: User successfully signed up and logged in
echo.
echo Starting Test 2: Login with correct credentials
echo 📍 Navigating to login page...
echo 🔍 Looking for login form...
echo 📝 Entering email and password...
echo 🚀 Clicking login button...
echo ❌ Test 2 failed: Login button not found
echo.
echo Starting Test 3: Dashboard accessibility
echo 📍 Navigating to dashboard...
echo ✓ Checking if dashboard elements are present...
echo ✅ Test 3 passed: Dashboard loaded successfully
) > test-sample.txt

rem Run the formatter
node format-test-results.js test-sample.txt test-sample.html

echo ✅ Sample HTML report generated: test-sample.html
echo 🌐 Open test-sample.html in your browser to see the formatted results

rem Clean up
del test-sample.txt

pause
